sleep 2;

_unit = _this select 0;

comment "Remove existing items";
removeAllWeapons _unit;
removeAllItems _unit;
removeAllAssignedItems _unit;
removeUniform _unit;
removeVest _unit;
removeBackpack _unit;
removeHeadgear _unit;
removeGoggles _unit;

comment "Add containers";
_unit forceAddUniform "CRYE_V3_Sleeved";
for "_i" from 1 to 4 do {_unit addItemToUniform "ACE_tourniquet";};
_unit addItemToUniform "ItemcTabHCam";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_IR_Strobe_Item";};
_unit addItemToUniform "ACE_Flashlight_MX991";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_epinephrine";};
for "_i" from 1 to 4 do {_unit addItemToUniform "ACE_CableTie";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_EarPlugs";};
_unit addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_quikclot";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_unit addItemToUniform "ACE_packingBandage";};
_unit addItemToUniform "ACE_SpraypaintGreen";
_unit addVest "milgp_v_marciras_teamleader_CB";
for "_i" from 1 to 6 do {_unit addItemToVest "ACE_personalAidKit";};
_unit addItemToVest "ACE_DefusalKit";
for "_i" from 1 to 2 do {_unit addItemToVest "11Rnd_45ACP_Mag";};
for "_i" from 1 to 10 do {_unit addItemToVest "DGR_224_MK318_30Rnd";};
_unit addBackpack "tfw_ilbe_blade_coy";
_unit addItemToBackpack "ACE_EntrenchingTool";
_unit addItemToBackpack "A3_GPNVG18b_TI";
_unit addItemToBackpack "ACE_EarPlugs";
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_quikclot";};
_unit addItemToBackpack "milgp_h_cap_03_goggles_RGR";
_unit addItemToBackpack "ACE_Clacker";
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 8 do {_unit addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_M84";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "HandGrenade";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_HandFlare_Green";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_HandFlare_Red";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_HandFlare_Yellow";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 4 do {_unit addItemToBackpack "ACE_Chemlight_HiYellow";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "Chemlight_green";};
for "_i" from 1 to 2 do {_unit addItemToBackpack "ACE_M14";};
_unit addItemToBackpack "DemoCharge_Remote_Mag";
_unit addHeadgear "milgp_h_opscore_04_goggles_RGR_hexagon";
_unit addGoggles "rhs_googles_black";

comment "Add weapons";
_unit addWeapon "SMA_MK18MOEBLKTAN";
_unit addPrimaryWeaponItem "SMA_supp1tan_556";
_unit addPrimaryWeaponItem "SMA_SFPEQ_MK18TOP_TAN";
_unit addPrimaryWeaponItem "sma_spitfire_03_rds_low_black";
_unit addPrimaryWeaponItem "SMA_Gripod_01";
_unit addWeapon "hgun_Pistol_heavy_01_F";
_unit addHandgunItem "muzzle_snds_acp";
_unit addHandgunItem "optic_MRD";
_unit addWeapon "Rangefinder";

comment "Add items";
_unit linkItem "ItemMap";
_unit linkItem "ItemCompass";
_unit linkItem "ACE_Altimeter";
_unit linkItem "tf_anprc148jem_2";
_unit linkItem "ItemcTab";
_unit linkItem "HI_NV_L_Shemagh_Tan";

comment "Set identity";
_unit setFace "asczHead_picleson_A3";
_unit setSpeaker "ace_novoice";
[_unit,"punisherblk"] call bis_fnc_setUnitInsignia;